language: java
deploy:
- provider: script
  script: bash release.sh
  on:
    branch: master
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_515142cb6f1b_key -iv $encrypted_515142cb6f1b_iv
  -in maven.asc.enc -out maven.asc -d
- gpg --import --passphrase ${GPG_PASSPHRASE} --batch maven.asc